version: '3.1'
volumes:
  data:
services:
  db:
    image: mariadb:lts-jammy
    environment:
      MYSQL_ROOT_PASSWORD: aponte
      MYSQL_DATABASE: aponte
      MYSQL_USER: aponte
      MYSQL_PASSWORD: aponte
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
