version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: meu-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aponte
      MYSQL_USER: ivan
      MYSQL_PASSWORD: '123'
    ports:
      - "3306:3306"
    volumes:
      - ./dados_mysql:/var/lib/mysql
