version: '3.1'

services:
  mariadb:
    image: mariadb:lts-jammy
    environment:
      MYSQL_ROOT_PASSWORD: aponte
      MYSQL_DATABASE: aponte
      MYSQL_USER: aponte
      MYSQL_PASSWORD: aponte
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: aponte
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    
volumes:
  data:
